### ISSUE TITLE
Magento not updating to website

### ISSUE THREAD

**Issue by Shannonh9** [magento/community-features#100]
I am trying to update product descriptions. I can update it on the back-end of Magento, however it will not update to the website. Do you know why or how this would happen?
Yes, I have flushed the cache. Twice. 
Still will not uploading to the website. I can NOT put in new products or update existing products.

**Comment by amansrivastava** [comment]
Have you checked description value at default, website or store level and did you try reindexing ?
Based on given issue detail, it should work after reindexing.

**Comment by sivaschenko** [comment]
Cannot reproduce this issue. Closing it for now. Please report a bug to https://github.com/magento/magento2/issues if you are still facing this issue
