### ISSUE TITLE
Include SQL wild cards by default when using 'like' in search criteria 

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/community-features#13]
As a developer, I don't want to think about passing SQL wildcard characters when sending 'like' search criteria through a request to the Product API.

### Preconditions
1. Magento CE 2.2.1

### Steps to reproduce
1. Install Magento CE 2.2.1
2. Install provided sample data using `bin/magento sampledata:deploy`
3. Remove WebApi security authorization in Admin > Stores > Configuration > Services > Magento WebApi
4. Make request to: `http://[magento host]/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=red&searchCriteria[filter_groups][0][filters][0][condition_type]=like`

### Expected result
1. Products with sku that contains 'red' are returned in the response xml.

### Actual result
1. No products returned.

**Original Report**: https://github.com/magento/magento2/issues/12456 by @nbennett25

**Comment by sivaschenko** [comment]
Duplicate https://github.com/magento/community-features/issues/12
