### ISSUE TITLE
Use a supported version of Elasticsearch

### ISSUE THREAD

**Issue by geerlingguy** [magento/community-features#141]
### Description (*)

In https://github.com/magento/magento2/issues/18974, it was reported that Elasticsearch 6.x versions are incompatible with Magento 2, and installations will silently fail the test connection, and you can't index or search Magento data with Elasticsearch 6 or later.

That issue was closed as it was not considered a bug that Magento supported Elasticsearch 2.x and 5.x and didn't work with 6.x.

[Elasticsearch 5.x's End-of-Life date is 2019-03-11](https://www.elastic.co/support/eol) (only a couple weeks away now), and so it will become harder and harder to use Magento with any version of Elasticsearch (especially in cloud environments) after that day arrives.

### Expected behavior (*)

* A supported version of Elasticsearch should be able to be used by Magento 2.x.
* The Magento UI for Elasticsearch allows you to select 'Elasticsearch 5.0+', which _implies_ 6 may work (since it's technically '5.0+'), so it would work with Elasticsearch 6.x.

### Benefits

* People would be able to use Magento 2.x with a modern, supported version of Elasticsearch.
* People would not have to spend many hours trying to figure out how to get Elasticsearch 5 or 2 running when it is not well supported in most cloud environments, and harder to install than the latest/supported version(s).

### Additional information

See upstream ticket which was closed: https://github.com/magento/magento2/issues/21277

**Comment by romainruaud** [comment]
I'm working on this one.
