### ISSUE TITLE
Magento Contributor Assistant (magento-engcom-team): Deploy Magento instance: add Elasticsearch option

### ISSUE THREAD

**Issue by fgagne** [magento/community-features#145]
### Description
The [Magento Contributor Assistant (magento-engcom-team)](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) allow to deploy Magento instance for testing issues. Here a sample from the documentation:

`@magento-engcom-team give me {$version} instance`

That instance is configured to use **MySQL** as the **Search Engine** and no Elasticsearch server is running. It's thus impossible to use that test facility for issues related to Elasticsearch which is now available in the CE (Community Edition) since 2.3 version. Further more, [the **MySQL** **Search Engine** is deprecated](https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html) and we can expect it will get removed further down the road.

In that context, it seems logical to add a option to deploy a Magento instance with a specific **Search Engine** (MySQL, Elasticsearch, Elasticsearch 5.0+).

### Expected behavior
Add a switch to specify the **Search Engine** (possible suggestion below)

`@magento-engcom-team give me {$version} instance with search-engine {mysql|elasticsearch|elasticsearch5}`

### Benefits
1. Better testing of PR and thus less bugs
2. Easier and less time consuming testing of the Steps to reproduce of issues
3. Faster closing of issues already fixed on develop branches

**Comment by sivaschenko** [comment]
Thanks for the feature request!

We are working on improving the deployer and adding this option as well as others is on our list.

Recently the editions and extensions arguments have been added to the deployer arguments. See the documentation https://devdocs.magento.com/contributor-guide/contributing.html#customize-deployed-instances

I am closing this issue as it is not related to magento2 repository and community will not be able to contribute towards it.
