### ISSUE TITLE
Output of setup:static-content:deploy contains red color, should be a friendlier color

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/community-features#15]
### Preconditions
1. macOS 10.12.6
2. iTerm2 3.1.5 with Solarized Dark theme
3. Magento 2.2.1
4. PHP 7.0.25

### Steps to reproduce
1. Setup a fresh Magento 2.2.1 installation
2. Execute: `bin/magento setup:static-content:deploy -f --theme Magento/blank en_US`

### Expected result
1. Output with friendly colors that don't give the impression that something went wrong

### Actual result
1. Seeing a bunch of red colors on the screen, which makes you think something went wrong.
![screen shot 2017-11-22 at 15 57 39](https://user-images.githubusercontent.com/85479/33133734-fa72b7f2-cf9d-11e7-9322-fcdf94945648.png)

### Discussion
I actually didn't notice this when working locally, but when deploying to a server. We see in the output of our deployment scripts a bunch of red colors, which almost always means something is going terribly wrong, but when looking closer at the output, it was just telling us what strategy is being used and how long it took.
I would suggest changing this color to something more friendly, like blue or green for example.
I don't know if there are some kind of Magento standards for the colors being used in the output of cli commands?

**Original Report**: https://github.com/magento/magento2/issues/12404 by @hostep

**Comment by korostii** [comment]
For those wondering, the issue has been resolved. Copied from [#12404](https://github.com/magento/magento2/issues/12404#issuecomment-370587933):

> The issue has been fixed in magento/magento2#13709 by @hostep in `2.2-develop` branch
> Related commit(s):
> d5490144c5d833827ac37ae6f7cc53c6ff4182ac
> 3733deada21670bd45626a91786b601994ec08e2
> The fix will be available with the upcoming 2.2.4 release.
