### ISSUE TITLE
Improve the performance of the method app/code/Magento/Eav/Model/Config.php::getAttribute

### ISSUE THREAD

**Issue by PierreLeMaguer** [magento/community-features#183]
**Description**

the method app/code/Magento/Eav/Model/Config.php::getAttribute is very often used everywhere in the website. For example, it is called 34 times in the checkout cart page. Each time, it makes an SQL request to get data from the table eav_attribute and another to get data from catalog_eav_attribute.

**The problem**
This method does not use EAV cache.

**benefits**
We earn time by getting the EAV cache instead of making SQL requests.

**Comment by kandy** [comment]
Implemented  by MC-16108: [Performance] EAV attribute is not cached https://github.com/magento/magento2/commit/c69aae4aeaac06cd887b5d40116b58f0d5b728b2
