### ISSUE TITLE
Improve dashboard charts

### ISSUE THREAD

**Issue by rhoerr** [magento/community-features#186]
### Description (*)
Following https://github.com/magento/magento2/issues/21599, Magento recently switched from the deprecated Google Charts API to generating static chart images via image-charts.com (https://github.com/magento/magento2/commit/f92c8fd2b031531bac32615ab80ca09a66665617).

That being said, the new charts are not in any way dynamic, and do not provide a user experience befitting an enterprise software package, for reasons including unclear labels, lack of gridlines, pixelation, branding, and poor styling.

For example, this is the current dashboard chart on a site running 2.3.2 Commerce:
![D-ZlZRuXsAMrRqp](https://user-images.githubusercontent.com/13335952/60476708-90a8b800-9c4a-11e9-903b-7a6f256c3b3b.png)

### Expected behavior (*)
Use a modern JavaScript chart library to build the dashboard charts on the client side.

### Benefits
Using a client-side JS chart library would provide a far superior user experience than the current static images, in design, interactivity (tooltips), and usefulness.

Doing so would also reducing any possible security or privacy concerns from the current approach, which involves sending data to or including a third-party-hosted resource or API for the same purpose. With a client-side library responsible for rendering the data, no data would leave the premises, and no external resources would be added in to the sensitive admin panel area.

### Additional information
There are numerous open-source JS chart libraries that would fit the purpose, including https://github.com/chartjs/Chart.js and https://github.com/flot/flot (both licensed MIT). My inclination would be Chart.js, given its more active contributor base, better documentation, and simple out-of-box responsive support.

In the process, the charts should also be switched from line to bar-type, to better reflect the nature of the underlying data (which is discrete sales figures, not continuous).

After integrating such a library, further improvements would be possible in the areas of changing timescale without reload; breaking down data by store; and more.

**Comment by ihor-sviziev** [comment]
@rhoerr
+1 for https://github.com/chartjs/Chart.js

Current charts are really terrible, I think no one will complain about improving existing chart and making them better and even interactive.

Would like to see such contribution from you 👍

**Comment by mortenbirkelund** [comment]
+1 for changing the default chart to give a better user experience.

**Comment by Bartlomiejsz** [comment]
@rhoerr @ihor-sviziev I'm working on Chart.js solution :) (not able to assign ticket to me here)
If there are any additional features that might be part of it besides better look and interactivity would be great to know!

**Comment by Bartlomiejsz** [comment]
![image](https://user-images.githubusercontent.com/9566840/73103647-d8e43c00-3ef4-11ea-8bd3-041fc3c071c9.png)

**Comment by rhoerr** [comment]
Sounds good. I started an implementation but ran into other commitments, didn't get far. Looks like you have good progress!

**Comment by Bartlomiejsz** [comment]
@rhoerr ohh, I didn't get from description that you were working on that also, good then that we aren't both doing same thing :)
Charts basically are working fine, I need to do some improvements, cleanup of existing classes and then the most fun part - tests 😊

**Comment by ihor-sviziev** [comment]
@sdzhepa could you assign @Bartlomiejsz to this issue, as I don’t have access to assign people either

**Comment by ihor-sviziev** [comment]
@Bartlomiejsz,
Is there any prototype? Maybe some "work in progress" pull request?

**Comment by Bartlomiejsz** [comment]
@ihor-sviziev I believe I have functionality ready, so I could create some initial PR today later I think. Just as first approach I used same classes that are used by current static images chart, I removed old functionality and added new and removed few classes no longer needed. Do you think such change could be accepted for 2.4 release or I should create completely new classes and deprecate old ones?

**Comment by ihor-sviziev** [comment]
Let’s create PR, I’ll review it and will provide you feedback

**Comment by Bartlomiejsz** [comment]
Done @ihor-sviziev - https://github.com/magento/magento2/pull/26923
I still see some possibility for improvements here, but please take a look and share your feedback if possible :)
