### ISSUE TITLE
Cannot select existing simple products for a new configurable product

### ISSUE THREAD

**Issue by tadhgbowe** [magento/community-features#208]
I am creating a new Configurable product via the Admin Panel (based on color). My simple products (children) already exist via a product import. When I click on "Edit Configurations" it takes me down the path of creating new simple variations. I don't want to do this. I simply want to select the existing products.

Interestingly if I go ahead and generate some simple variations via the "Edit Configurations" after the product save I can see a new link "Add Products Manually" beside "Edit Configurations". That's what I want to see the first time around after I inform it that the new configurable product is based on color.

The "Edit Configurations" wizard needs to allow me to select existing products after I've told it what configurable attributes I'm working with e.g. color or size.

Is this a known issue?

Thanks
Tadhg

### Preconditions

1. Have a configurable product with no simples attached

### Steps to reproduce

1. Have a configurable product
2. Click on Edit configurations
3. Go to step 4
4. no way to add simples.

### Expected result

1. abbility to add simple products instead of fake product first
2. then remove fake product and and simples

### Actual result

1. No button to add simple product directly
![image](https://user-images.githubusercontent.com/726557/36781557-77dca142-1c76-11e8-9a1a-791c5e4b8243.png)

**Comment by sunilit42** [comment]
@joosttissen @melvinio 

https://github.com/magento/magento2/pull/27630

sorry for late,but you can use that solve your problem

**Comment by arkreddy2005** [comment]
Hi Sunil,

I checked same in 2.3.4 and it's not associated

Issue :

go to catalog -> Manage products -> Add New Configurable product
Select "Add Products Manually" option without creating configurable options and save product
Selected Associated products were not associated to newly created product
Expected :

go to catalog -> Manage products -> Add New Configurable product
Select "Add Products Manually" option without creating configurable options and save product
Selected Associated products should display in newly created product

**Comment by sunilit42** [comment]
@arkreddy2005 

have you checked with my code?

**Comment by PiscesThankIT** [comment]
I create a module and add a step to Create Configurations which will allow skipping generating configurable products and adding products manually.
See here: https://github.com/PiscesThankIT/ThankIT_ConfigurableWizard
![step-optional](https://user-images.githubusercontent.com/20181723/82185348-a8993100-991b-11ea-9c68-bfdd3523814f.png)
![step-optional2](https://user-images.githubusercontent.com/20181723/82185357-aa62f480-991b-11ea-9a25-457c1d5b4700.png)

**Comment by rintoug** [comment]
This issue still exists in  Magento community ver. 2.3.5-p1 after almost 5 years since this ticket open.

**Comment by sivaschenko** [comment]
Moved to magento2 repo for development https://github.com/magento/magento2/issues/30809

**Comment by mobweb** [comment]
This has been "closed as completed" but as far as I can tell the original issue is still present as of today?
