### ISSUE TITLE
Add PHPStan to Magento static checks

### ISSUE THREAD

**Issue by larsroettig** [magento/community-features#211]
### Summary (*)
As the architecture team discussed at https://github.com/magento/architecture/pull/114
we should add PHPStan as developer composer dependencies.

**How:** 
`composer require --dev phpstan/phpstan`
Add check to `dev/tests/static/phpunit.xml.dist`

### Expected behaviour (*)
PHPStan run with the Magento static checks

### Actual result (*)
Php Stan is not installed and does not run with the  static checks

### Benefits

Following types of issues can be found in Magento codebase:
the use of undefined class;
call to undefined function;
missing parent::__construct() call;
passed arguments mismatch, etc.

### Additional information
The Drupal people also picked up phpstan, read some insights
https://glamanate.com/blog/writing-better-drupal-code-static-analysis-using-phpstan

**Comment by lenaorobei** [comment]
PHPStan was added to Magento https://github.com/magento/magento2/blob/2.4-develop/composer.json#L95
