### ISSUE TITLE
Elasticsearch Admin version dropdown needs clarification

### ISSUE THREAD

**Issue by dobooth** [magento/community-features#231]
In the Magento admin, you can choose your Elasticsearch version.
https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-config-nginx.html#configure-elasticsearch-within-magento
In the dropdown, you have a value like "6.0+". 
This is not clear enough. It is supposed to mean "all of v6" but it actually means "all versions 6 and higher".
Now that Elasticsearch is up to version 7, users are not sure whether we support v7, which we do not as of yet.
I suggest that we change the dropdown version numbers to a "6.x" format.
Also, ES v5 is EOL and should be removed, since PCI forbids EOL software.
It is unclear what the generic "Elasticsearch" option is for.

**Comment by Bartlomiejsz** [comment]
Hi @dobooth, isn't that already fixed by https://github.com/magento/magento2/commit/cf1b0845fd7d0c083b5f20ba2c0a495d0e9bf9ad#diff-b2e0d454e4ffd542fa96dc1b7dc225d9 ?

**Comment by dobooth** [comment]
Yes, it stems from https://github.com/magento/magento2/issues/25674
