### ISSUE TITLE
Catalog price rule per store/store view

### ISSUE THREAD

**Issue by Zyles** [magento/community-features#237]
Why can't you create price rules based on store/store view?

It makes no sense to run promotions on a website level only.

If you have two stores, one in different languages you may not be able to run the same promotions on both because of restrictions.

Magento 2 needs to support store and storeview level promotions.

**Comment by kandy** [comment]
Magento is not support Prices on store level.
So  is no make sense to implement Catalog price rule per store/store view, before introduce price on store level

**Comment by sivaschenko** [comment]
The price is not supported on store/store view level in Magento, so we cannot implement promotions based on these levels
