### ISSUE TITLE
Add performance check for pull requests

### ISSUE THREAD

**Issue by ilnytskyi** [magento/community-features#242]
Sometimes contributors fix not only bugs but performance issues as well.
I happens that when the bug fixed the code is not that fast.
Many thing can happen e.g.
- The class loads heavy object as new dependency
- The execution result is not cached when it can be called more than once with the same parameters
- Redundant queries added
- The new plugin or event observer slows the main method execution time

I think that performance is important for magento and those issues can be identified before the merge or release.

![Selection_057](https://user-images.githubusercontent.com/3192770/75091672-68baeb80-5570-11ea-94fc-20d5ad03f4d6.png)

This check can be optional or required. At least it would show us if introduced changes affect performance.
- Some tests can load different pages with disabled FPC and HTML_BLOCK cache or other types of configuration.
- It can count the number of DB queries on different pages
- It can call API and measure if the response time changed
- different metrics can be used
- maybe it will be possible to measure JS time load 
- etc.

This way maintainers and community can have information about performance changes.
Some contributors may focus on fixing performance issues (may be special award can be introduced ?)

**Comment by adifucan** [comment]
Hi @ilnytskyi we have performance checks for internal PR (count of DB queries, execution time of frontend and backend scenarios, graphql execution time, storefront sitespeed.io metrics, JS requests count, JS execution time, CSS metrics, API scenarios metrics etc). 
But yes unfortunately currently we do not have performance checks for community PRs. As far as I know adding performance checks to community PRs is already in progress now. @slopukhov @andimov can you tell about the status of this issue?

**Comment by andimov** [comment]
Thanks @adifucan for the answer on this feature. We are going to start working with integration of performance builds to the same ecosystem soon. It will allow us to receive triggers for the performance builds in the same way and provide the results.
We are expecting the whole functionality should be added in 2-3 months.

**Comment by sivaschenko** [comment]
@ilnytskyi thanks for the feature request!

The performance tests are executed by us on each delivery to the mainline codebase. The tests are executed on the internal bulk pull request delivery stage as currently, we don't have the capacity to run it on each pull request.
