### ISSUE TITLE
In-Store Pickup functionality (aka Click and Collect)

### ISSUE THREAD

**Issue by tcmax76** [magento/community-features#246]
We've been wrestling with In-Store pickup ever since we migrated to Magento 2 from Magento 1 three years ago. This is a huge part of online business these days and, as such, should be an in-built functionality in Magento (I believe there was something included with Magento Shipping at one point, but since that's no longer around I assume Click and Collect isn't either?). Since it's not built in, we've been left trying to navigate third party extensions, none of which work exactly as a customer would expect.

Most third-party in-store pickup extensions just add an in-store pickup module to the Shipping Methods in Magento. This is problematic for two reasons:

1. It requires that customers enter a shipping address for the order, which can be confusing for the customer since the order is not, in fact, shipping, and also requires more work for the customer.
2. Because the shipping address is whatever the customer entered and not the store address, local taxes on the order (which should be based on the store address for in-store pickup orders) do not calculate correctly.

The module we've been using, Wyomind's Pickup @ Store extension, gets things mostly right. It asks the customer at the start of checkout if the order is for In-Store Pickup or to be shipped. Then, if it's in-store pickup, it adds the selected store's address in the shipping fields behind the scenes and requires customers to enter their billing address to the order. However, this extension isn't compatible with some payment method functions we'd like to use, such as PayPal and Braintree's Vault.

All of this is to say, Magento should offer this functionality out of the box. It's long overdue, and the fact that it's not there is one of several factors leading us to investigate switching to a different ecommerce platform.

**Comment by sivaschenko** [comment]
Thanks for the feature request @tcmax76 !

The InStore pickup functionality have been implemented as part of https://github.com/magento/inventory

Closing as done
