### ISSUE TITLE
Create static test for action controllers

### ISSUE THREAD

**Issue by lenaorobei** [magento/community-features#252]
### Description (*)
Due to recent changes in https://github.com/magento/magento2/pull/26778#issuecomment-592766350 need to create static test that will check that controller classes implement `ActionInterface` and do not extend `Action` abstract class.

### Expected behavior (*)
Static check fails if controller class extends `Action`.

### Benefits
This will prevent using of deprecated `ActionInterface`.

**Comment by swnsma** [comment]
Hi @lenaorobei,
Could you please clarify next:
- test must works only for files related to a PR;
- test must works only for created files and ignore modified files;
Am I right?

**Comment by naydav** [comment]
> Hi @lenaorobei,
> Could you please clarify next:
> 
> * test must works only for files related to a PR;
> * test must works only for created files and ignore modified files;
>   Am I right?

Hi @swnsma,

Sorry for the misunderstanding but the final decision about the controllers is still in active discussion. Thus, this task is not ready for development.

**Comment by lenaorobei** [comment]
Hi @swnsma,
Sorry for the delay.
Answering your questions.

> test must works only for files related to a PR
 
Yes

> test must work only for created files and ignore modified files;

Yes, you are right.

Thanks a lot for working on this.

**Comment by swnsma** [comment]
Here we go: https://github.com/magento/magento2/pull/29339

**Comment by ihor-sviziev** [comment]
https://github.com/magento/magento2/pull/26778 was already merged, so basically we have such static test.
@lenaorobei @naydav @sdzhepa could you close this issue?

**Comment by lenaorobei** [comment]
@ihor-sviziev yes, sure!

Thanks again @swnsma! That's a great improvement.
