### ISSUE TITLE
Implement a MediaFileStorageInterface to abstract media storage (file read, write, delete)

### ISSUE THREAD

**Issue by woutersamaey** [magento/community-features#255]
Implement a MediaFileStorageInterface to abstract media storage (file read, write, delete).
This way it is easier to implement using files directly from cloud storage like Amazon S3 and others.

**Comment by kandy** [comment]
Support of S3 (other blob storage can be added as well)  was added to Magento Core so I close this ticker as resolved.
Please pay attention that it was implemented on FileSystem level, and we think about deprecation of MediaStorage module

**Comment by sidolov** [comment]
I'm closing the issue since it's already implemented.
