### ISSUE TITLE
Delete all products, orders, customers etc

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magento/community-features#277]
Is there a n98 mage run script or some button somewhere in Magento to clean up a dev/testing site prior to going live with real data?

Yes could delete via SQL but not sure if this would work for all extensions e.g. what if they don't have FK on delete cascade?
https://magento.stackexchange.com/questions/222487/how-to-delete-all-products-in-magento-2-and-start-product-id-from-1

**Comment by hostep** [comment]
We use the [stripped database dump feature](https://github.com/netz98/n98-magerun2#stripped-database-dump) of the `db:dump` command of [n98-magerun2](https://github.com/netz98/n98-magerun2) and add the `@trade` and `@stripped` groups in there, then we get a database dump without sales & customer data, it works pretty well.
Third party database entries will need some extra work though, but you can also specify those particular tables to be stripped out.

**Comment by sivaschenko** [comment]
HI @LiamKarlMitchell this repository is for the feature requests to Magento 2 project.

Please reach out to slack, https://community.magento.com/ or https://magento.stackexchange.com/ for collaboration on questions resolutions and discussion (there is also much more audience that can address the question as well).

Closing this issue as it's not a feature request
