### ISSUE TITLE
Ability to Reset All Filters in Orders Page

### ISSUE THREAD

**Issue by thorrrr** [magento/community-features#281]
Description (*)
We use the order screen all day and apply filters. For some reason this page does not have a reset all filters option!
But you other search areas do!
We have to click each filter individually to remove it which results in a full page refresh.
Having just moved from M1 i feel like i have gone back 10 years with the speed its painfully slow to refresh.
But if i have 3 to 5 filters this takes a long time.

Expected behaviour (*)
I would expect a standard reset all filters button

Benefits
Efficiency and speed of use it just needs one not sure how it was ever missed out

**Comment by sivaschenko** [comment]
Hi @thorrrr thanks for the report.

There is "Clear all" link that resets all the filters for order grid. The link is located in the applied filters section on the right:
![image](https://user-images.githubusercontent.com/2028541/95985469-8baa5080-0e1c-11eb-884b-0c9b61d53946.png)

Let me know if that resolves the issue

**Comment by thorrrr** [comment]
HI

I do not see this in my version

[image: image.png]

**Comment by thorrrr** [comment]
Can you tell me where to put the code to display it so i can pass it on to
my Dev

**Comment by sivaschenko** [comment]
What is your version, @thorrrr ?

**Comment by SolsWebdesign** [comment]
Beste meneer, mevrouw,

Van maandag 19 oktober t/m zondag 25 oktober ben ik i.v.m. de vakantieperiode minder goed bereikbaar. Uw e-mails worden wel gelezen, echter het kan zijn dat een reactie wat langer op zich laat wachten.
Voor dringende zaken kunt u bellen met +31 6 24 888 006.
vr.groeten,
Isolde

**Comment by sivaschenko** [comment]
I have to close this issue as it's not applicable to the latest Magento version, that means it's already fixed.

Please consider upgrading your Magento version.
