### ISSUE TITLE
Temporary tables as engine = MEMORY ?

### ISSUE THREAD

**Issue by MyZeD** [magento/community-features#291]
### Summary (*)
How we all know is the magento 2 shopsystem not the fastest on the market.
Every minutes is running the index or something else and creates, renames, drop temporary tables.
This is not an overkill, but use to capacity the HDD/SSD.

### Examples (*)
CREATE TABLE IF NOT EXISTS `catalogsearch_fulltext_scope2` [...]
CREATE TABLE IF NOT EXISTS `catalogsearch_fulltext_scope5` [...]
INSERT INTO `catalog_category_product_index_store2_replica` [...]
TRUNCATE TABLE `catalog_category_product_index_store1_replica` [...]
ALTER TABLE catalog_category_flat_store_11 RENAME TO catalog_category_flat_store_11_old [...]

### Proposed solution
Would it help, to create this tables directly as Memory-Tables as Engine ?
This would be a makes all faster and more weight-light.
If the Server or Database crashes - after this the PHP-Script doesn't do anything with it and let it as trash back in the database.

What do you think about it ?

**Comment by woutersamaey** [comment]
The MEMORY storage engine is not supported on a MySQL if GTID is enabled. So in my opinion, this feature should only be used if MySQL is configured not to use GTID. This can be dynamically queried.
