### ISSUE TITLE
Searchable textbox in dropdown attribute

### ISSUE THREAD

**Issue by Zyles** [magento/community-features#306]
Make the **_dropdown attribute type_** searchable, just like the attribute set dropdown.

It becomes REALLY annoying when you have 100 dropdown options to select from.

This:

![image](https://user-images.githubusercontent.com/1741593/73578301-97690900-447f-11ea-97da-83855be14914.png)

To this:

![image](https://user-images.githubusercontent.com/1741593/73578281-8ae4b080-447f-11ea-9d83-81e8914fe035.png)

**Comment by sivaschenko** [comment]
Duplicate to https://github.com/magento/community-features/issues/234
