### ISSUE TITLE
VAT rules based on value (for UK after Brexit)

### ISSUE THREAD

**Issue by YiffyToys** [magento/community-features#317]
Since 2021-01-01 good imported to the UK require the seller to pay UK VAT if and only if the value is <136 GBP.

Source: https://www.gov.uk/government/publications/changes-to-vat-treatment-of-overseas-goods-sold-to-customers-from-1-january-2021/changes-to-vat-treatment-of-overseas-goods-sold-to-customers-from-1-january-2021

The currene Magento2 tax rule system can make an exception for northern ireland based on ZIP code ("BT*")
but it can no handle this rule since tax rules and customer tax classes can not depend on the value of a shipment.

**Comment by hostep** [comment]
Also see:
- https://github.com/magento/magento2/issues/31746
- https://github.com/magento/magento2/issues/31745

**Comment by YiffyToys** [comment]
31746 seems to match, Thanks.
31745 is something else entirely.
