### ISSUE TITLE
Magento 2 and SSL connection to MySQL

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/community-features#61]
### Preconditions
1. Magento 2.2.2 
2. MySQL 5.7.x

### Steps to reproduce
1. In env.php there should be a way to specify optional secure connection details which can then be used: 

```
$this->resource->ssl_set($clientKey, $clientCert, $caCert, $caPath, $cipher);
```

To establish a secure connection to mysql.

### Expected result
1. Secure connection

### Actual result
1. I don't believe this is supported?

Example of what I mean:
https://stackoverflow.com/questions/9738712/connect-to-remote-mysql-server-with-ssl-from-php
http://blog.machek.co.uk/2016/06/php-with-mysql-and-ssl.html

**Original Report**: https://github.com/magento/magento2/issues/13561 by @craigcarnell

**Comment by bnymn** [comment]
There is a PR aiming to solve this issue.

https://github.com/magento/magento2/pull/14660

**Comment by sdzhepa** [comment]
PRs to fix https://github.com/magento/magento2/issues/13561
- https://github.com/magento/magento2/pull/25398 
- https://github.com/magento/magento2/pull/18075

have been merged into develop branch.

**Comment by onepack** [comment]
What would be the procedure to connect to an external database on an existing install where SSL-communication is enabled.
What config settings are needed in the env.php?
