### ISSUE TITLE
When creating configurable products I cannot add simple products directly

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/community-features#65]
### Preconditions

1. Have a configurable product with no simples attached
2. Magento ver. 2.1.10

### Steps to reproduce

1. Have a configurable product
2. Click on Edit configurations
3. Go to step 4
4. no way to add simples.

### Expected result

1. abbility to add simple products instead of fake product first
2. then remove fake product and and simples

### Actual result

1. No button to add simple product directly
![image](https://user-images.githubusercontent.com/726557/36781557-77dca142-1c76-11e8-9a1a-791c5e4b8243.png)

**Original Report**: https://github.com/magento/magento2/issues/13882 by @robbertstevens

**Comment by orismology** [comment]
I cannot believe how unintuitive this is coming from Magento 1. In Magento 1, we used to just be able to use the "Quick simple product creation" to quickly add a new simple product. 

This new system becomes particularly annoying when you do not have a product for each of the variations. If we have a Large Shirt in Blue and Red, and a Small Shirt in Blue and Green. Magento 2 insists on creating a Large Green and a Small Red, which we then have to manually disable!

Plus, the new checkboxes when creating a simple product in this manner are awful. We have over 100 different colours, and it is now an impossibly large list to work through. An autocomplete dropdown box similar to the category picker would be so much better for this task.

**Comment by sivaschenko** [comment]
Duplicate to https://github.com/magento/community-features/issues/208
