### ISSUE TITLE
Cache invalidates after a while also when product or category edit is done.

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/community-features#66]
### Preconditions

1. Magento 2.2.3 
2. PHP 7.1
3. Plesk with Varnish 4.0 Docker
4. Running in Developer Mode (but also tested in Production)

### Steps to reproduce
1. Activate Varnish or use Internal Page cache (result the same). 
2. Warm the Cache
3. Check if CMS Pages, Category Pages and Product Pages are warmed.

### Expected result
1.  Cached pages shoukd stay warmed at least for few hours/a day depending on TTL that has been set.
2. Weh editing a product or category cache should not get flushed.

### Actual result
1. After edit (product, category) all cache is gone.
2. After little while at about 30 minutes cache is invalidated.

I have tried all kinds of solutions but no luck.

Can this be a setup issue? Or is there a proper way to check this. When cache is there site is super fast.

**Original Report**: https://github.com/magento/magento2/issues/13996 by @KooTjoo

**Comment by TimQSO** [comment]
No update on this one?

**Comment by sivaschenko** [comment]
This seems to be correct Magento behaviour. The cache is invalidated when updating entities to reflect the updates on the frontend. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
