### ISSUE TITLE
[FEATURE]Rial currency must not have .00 at the end

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/community-features#69]
Persian Rial Currency does not have .00 at the end meaning that for example 21.00 is not applicable
the rial currency is such 34000 Rial
5400Rial

there is a comma delimiter that is arbitrary for any thousand 
for example 34,000
5,400
9,360,764
but there shoudn't be .00 at the end since  does not have any value
### Preconditions

1. magento 2.3.x
2. magento 2.2.x
3. magento 2.1.x
4. magento 2.0.x

### Steps to reproduce

1. on admin go to catalogue
2. on frontend on prices secton
3. 

### Expected result

1. a pricing such as 34,000 or 5,400

### Actual result

1. there is .00 at the end of all prices such as 34,000.00 which the .00 must be omitted

**Original Report**: https://github.com/magento/magento2/issues/14070 by @woshka

**Comment by sivaschenko** [comment]
Duplicate to https://github.com/magento/magento2/issues/21725 (The same solution needs to be applied for all currencies with non-default precision)
