### ISSUE TITLE
Missing "use default" checkbox for product images when overriding on store view level

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/community-features#82]
### Preconditions
1. Tested in Magento 2.2.4
2. Have a product with images on it

### Steps to reproduce
1. Edit a product
2. Switch to a certain store view scope
3. Edit the primary image for the product
4. There is no "Use default" checkbox, to use the product images as entered on the global scope

### Expected result
1. Allow us to reset product images to the parent or global scope, just like any other attribute

### Actual result
1. Screenshot: 
![image](https://user-images.githubusercontent.com/71019/43506897-e529a5f6-956b-11e8-96dc-e8b9b74c7766.png)

**Original Report**: https://github.com/magento/magento2/issues/17303 by @woutersamaey

**Comment by sivaschenko** [comment]
Duplicate to https://github.com/magento/community-features/issues/23
