### ISSUE TITLE
Checkout data (shipping address etc) not persistant after cart update

### ISSUE THREAD

**Issue by Rickertje** [magento/community-features#87]
### Preconditions
1. M2.2.5

### Steps to reproduce
1. Put item in cart
2. Go to checkout
3. Enter shipping address
4. Press Next to go to checkout step 2
5. Return to the store
6. Go to checkout (customer data still present - which is GOOD)
7. Return to the store
8. Add or delete an item or update the cart in some other way
9. Go to checkout

### Expected result
1. Checkout data (shipping address etc) still here / persistent

### Actual result
1.  Checkout data is gone - which ofcourse is a GIANT dealbreaker. We want to keep the checkout data that was enterd by the customer to be persistent at all times.

Original report: https://github.com/magento/magento2/issues/18100

**Comment by somat211** [comment]
I am working on this task. I will update once it gets done.

**Comment by Rickertje** [comment]
@somat211 can you give me an update on this one please?

**Comment by sdzhepa** [comment]
Hello @Rickertje and @somat211 

Initial ticket magento/magento2#18100 was moved to "Feature Requests"  track

Please see/track progress in the scope of moved ticket https://github.com/magento/community-features/issues/118

Close this one as a duplicate.

Thank you for collaboration
