### ISSUE TITLE
Content Type x-www-form-urlencoded allowed for Api REST

### ISSUE THREAD

**Issue by i4rebecamartinez** [magento/community-features#92]
Summary

Content type x-www-form-urlencoded for API Rest calls are not allowed as Magento does not have any deserializer.

Proposed solution

Add new deserializer class for this type of request, and include new type in deserializers argument of Magento\Framework\Webapi\Rest\Request\DeserializerFactory.
  

Code content in https://github.com/magento/magento2/pull/18463

**Comment by ihor-sviziev** [comment]
Use case from https://github.com/magento/magento2/pull/18463#issuecomment-553445572
> I have recently come across a need for this were we provided an API endpoint for a payment gateway to notify us of order statuses. Unfortunately I had no control of the headers they sent in their updates and the API would throw a 500 error when the header was application/x-www-form-urlencoded.

**Comment by ihor-sviziev** [comment]
I think this issue should be closed with resolution "won't fix". Described detailed in https://github.com/magento/magento2/pull/18463#issuecomment-638634757

@sdzhepa could you close this issue?

**Comment by sivaschenko** [comment]
Closed based on the discussion above
